# Generated by Django 3.1 on 2020-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('restaurant', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
