# Generated by Django 3.1 on 2020-08-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_auto_20200816_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default='http://placehold.it/700x400'),
        ),
    ]
