# Generated by Django 3.1 on 2020-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0003_auto_20200816_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default='http://placehold.it/700x400', upload_to=''),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
